# Generated by Django 5.2.3 on 2025-09-07 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_availablemodules_is_active'),
        ('school', '0004_populate_classes'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureoffered',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.availablemodules'),
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='subscriptio_school__ca5032_idx',
        ),
        migrations.AlterUniqueTogether(
            name='packageversion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='status',
        ),
        migrations.AddField(
            model_name='featureoffered',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='featureoffered',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='featureoffered',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='packageversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='packageversion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='packageversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='packageversion',
            name='version_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('trial', 'Trial'), ('paid', 'Paid')], default='free', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('bank_transfer', 'Bank Transfer'), ('free', 'Free'), ('trial', 'Trial'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['school'], name='subscriptio_school__0b2d82_idx'),
        ),
        migrations.AddConstraint(
            model_name='packageversion',
            constraint=models.UniqueConstraint(fields=('package', 'version'), name='unique_package_version'),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
