# Generated by Django 5.2.3 on 2025-08-02 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'school_board',
            },
        ),
        migrations.CreateModel(
            name='SchoolDefaultClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'db_table': 'school_default_classes',
            },
        ),
        migrations.CreateModel(
            name='SchoolDefaultSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'school_default_subjects',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'school_academic_year',
                'ordering': ['start_year', 'end_year'],
                'unique_together': {('start_year', 'end_year')},
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('school_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='SchoolBoardMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolboard')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
            options={
                'db_table': 'school_board_mapping',
            },
        ),
        migrations.AddField(
            model_name='school',
            name='boards',
            field=models.ManyToManyField(related_name='schools', through='school.SchoolBoardMapping', to='school.schoolboard'),
        ),
        migrations.CreateModel(
            name='SchoolDbMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=255, unique=True)),
                ('db_user', models.CharField(max_length=100)),
                ('db_password', models.CharField(max_length=100)),
                ('db_host', models.CharField(default='127.0.0.1', max_length=100)),
                ('db_port', models.IntegerField(default=5432)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='school.school')),
            ],
            options={
                'db_table': 'school_db_metadata',
            },
        ),
        migrations.CreateModel(
            name='SchoolSyllabusEbooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebook_type', models.CharField(choices=[('single', 'Single'), ('chapter_wise', 'Chapter Wise')], max_length=50, null=True)),
                ('ebook_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('syllabus_year', models.IntegerField(blank=True, null=True)),
                ('chapter_number', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolboard')),
                ('class_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schooldefaultclasses')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schooldefaultsubjects')),
            ],
            options={
                'db_table': 'school_syllabus_ebooks',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveIntegerField()),
                ('chapter_name', models.CharField(max_length=200)),
                ('ebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schoolsyllabusebooks')),
            ],
            options={
                'db_table': 'syllabus_chapter',
                'ordering': ['chapter_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_topics', to='school.chapter')),
            ],
            options={
                'db_table': 'syllabus_sub_topic',
                'ordering': ['chapter', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='school.chapter')),
            ],
            options={
                'db_table': 'syllabus_prerequisite',
                'ordering': ['chapter', 'topic'],
                'abstract': False,
                'unique_together': {('chapter', 'topic')},
            },
        ),
        migrations.AddConstraint(
            model_name='schoolboardmapping',
            constraint=models.UniqueConstraint(fields=('school', 'board'), name='unique_school_board'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolsyllabusebooks',
            unique_together={('board', 'subject', 'class_number', 'ebook_name', 'created_at')},
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('chapter_number', 'ebook')},
        ),
        migrations.AlterUniqueTogether(
            name='subtopic',
            unique_together={('chapter', 'name')},
        ),
    ]
