# Generated by Django 5.2.3 on 2025-07-02 18:03

from django.db import migrations
from django.core.management import call_command

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'school_boards.json')

class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_school_admin'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
