# Generated by Django 5.2.3 on 2025-09-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_populate_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsyllabusebooks',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
