# Generated by Django 5.2.3 on 2025-07-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_school_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldbmetadata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
