# Generated by Django 5.2.3 on 2025-07-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_schoolboardmapping_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolsyllabusebooks',
            unique_together={('board', 'subject', 'class_number', 'ebook_name', 'created_at')},
        ),
        migrations.AddField(
            model_name='schoolsyllabusebooks',
            name='syllabus_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
