# Generated by Django 5.2.3 on 2025-07-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_schoolsyllabusebooks_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsyllabusebooks',
            name='chapter_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
