# Generated by Django 5.2.3 on 2025-08-02 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('classes', '0002_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveIntegerField()),
                ('chapter_name', models.CharField(max_length=200)),
                ('school_board_id', models.IntegerField()),
                ('ebook_id', models.IntegerField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolacademicyear')),
                ('class_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.schoolclass')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.subject')),
            ],
            options={
                'db_table': 'syllabus_chapter',
                'ordering': ['chapter_number'],
                'abstract': False,
                'unique_together': {('school_board_id', 'academic_year', 'chapter_number', 'class_number', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='SchoolClassPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus.schoolchapter')),
                ('class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.schoolsection')),
            ],
            options={
                'db_table': 'classwise_prerequisite',
                'ordering': ['chapter', 'topic'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolClassSubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus.schoolchapter')),
                ('class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.schoolsection')),
            ],
            options={
                'db_table': 'classwise_sub_topic',
                'ordering': ['chapter', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='syllabus.schoolchapter')),
            ],
            options={
                'db_table': 'syllabus_prerequisite',
                'ordering': ['chapter', 'topic'],
                'abstract': False,
                'unique_together': {('chapter', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='SchoolSubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_topics', to='syllabus.schoolchapter')),
            ],
            options={
                'db_table': 'syllabus_sub_topic',
                'ordering': ['chapter', 'name'],
                'abstract': False,
                'unique_together': {('chapter', 'name')},
            },
        ),
    ]
