# Generated by Django 5.2.3 on 2025-08-06 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_populate_classes'),
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclassprerequisite',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_prerequisites', to='syllabus.schoolchapter'),
        ),
        migrations.AlterField(
            model_name='schoolclasssubtopic',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_sub_topics', to='syllabus.schoolchapter'),
        ),
        migrations.CreateModel(
            name='SchoolLessonPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('learning_outcomes', models.TextField()),
                ('real_world_applications', models.TextField()),
                ('taxonomy_alignment', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('started', 'Started'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_chapter_lesson_plan_days', to='syllabus.schoolchapter')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_class_lesson_plan_days', to='classes.schoolsection')),
            ],
            options={
                'db_table': 'school_lesson_plan_day',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('time_minutes', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_lesson_topics', to='syllabus.schoollessonplanday')),
            ],
            options={
                'db_table': 'school_lesson_topic',
            },
        ),
    ]
