# Generated by Django 5.2.3 on 2025-08-15 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_alter_schoolclassprerequisite_chapter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteboardSession',
            fields=[
                ('session_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whiteboard_sessions', to='syllabus.topic')),
            ],
            options={
                'db_table': 'whiteboard_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhiteboardDataChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=list)),
                ('chunk_index', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_chunks', to='syllabus.whiteboardsession')),
            ],
            options={
                'db_table': 'whiteboard_data_chunk',
                'ordering': ['chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='whiteboardsession',
            index=models.Index(fields=['session_id'], name='whiteboard__session_e9ba76_idx'),
        ),
        migrations.AddIndex(
            model_name='whiteboardsession',
            index=models.Index(fields=['topic'], name='whiteboard__topic_i_1f2086_idx'),
        ),
        migrations.AddIndex(
            model_name='whiteboarddatachunk',
            index=models.Index(fields=['session', 'chunk_index'], name='whiteboard__session_86a4fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='whiteboarddatachunk',
            constraint=models.UniqueConstraint(fields=('session', 'chunk_index'), name='unique_session_chunk_index'),
        ),
    ]
