# Generated by Django 5.2.3 on 2025-08-21 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0003_whiteboardsession_whiteboarddatachunk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lesson_plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='syllabus.schoollessonplanday')),
            ],
            options={
                'db_table': 'chat_session',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='syllabus.chatsession')),
            ],
            options={
                'db_table': 'chat_message',
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['lesson_plan_day'], name='chat_sessio_lesson__e6cbd7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user_id'], name='chat_sessio_user_id_beb7da_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session'], name='chat_messag_session_389d44_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['role'], name='chat_messag_role_9cd150_idx'),
        ),
    ]
