# Generated by Django 5.2.3 on 2025-08-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0004_chatsession_chatmessage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='summary',
        ),
    ]
