# Generated by Django 5.2.3 on 2025-07-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0005_remove_schoolclassprerequisite_unique_chapter_topic_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolchapter',
            name='ebook_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
