# Generated by Django 5.2.3 on 2025-09-07 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0005_remove_chatsession_summary'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='whiteboardsession',
            name='whiteboard__topic_i_1f2086_idx',
        ),
        migrations.RemoveField(
            model_name='whiteboardsession',
            name='topic',
        ),
        migrations.AddField(
            model_name='whiteboardsession',
            name='lesson_plan_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whiteboard_sessions', to='syllabus.schoollessonplanday'),
        ),
        migrations.AddIndex(
            model_name='whiteboardsession',
            index=models.Index(fields=['lesson_plan_day'], name='whiteboard__lesson__4bc5ab_idx'),
        ),
    ]
