# Generated by Django 5.2.3 on 2025-09-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0006_remove_whiteboardsession_whiteboard__topic_i_1f2086_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoollessonplanday',
            name='taxonomy_alignment',
            field=models.TextField(),
        ),
    ]
