# Generated by Django 5.2.3 on 2025-10-14 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0007_alter_schoollessonplanday_taxonomy_alignment'),
        ('teacher', '0011_exam_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoollessonplanday',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher'),
        ),
    ]
