# Generated by Django 5.2.3 on 2025-08-11 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon')], max_length=1)),
                ('present', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='student.student')),
            ],
            options={
                'db_table': 'student_attendance',
                'indexes': [models.Index(fields=['date'], name='student_att_date_1ee40f_idx'), models.Index(fields=['session'], name='student_att_session_9c5889_idx'), models.Index(fields=['student', 'date'], name='student_att_student_39038c_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'date', 'session'), name='unique_student_date_session')],
            },
        ),
    ]
