# Generated by Django 5.2.3 on 2025-08-24 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon')], max_length=1)),
                ('is_holiday', models.BooleanField(default=False)),
                ('taken_by_user_id', models.IntegerField(blank=True, null=True)),
                ('updated_by_user_id', models.IntegerField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.schoolacademicyear')),
            ],
            options={
                'db_table': 'student_attendance',
            },
        ),
        migrations.CreateModel(
            name='StudentAttendanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_data', to='student.studentattendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='student.student')),
            ],
            options={
                'db_table': 'student_attendance_data',
            },
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['date'], name='student_att_date_1ee40f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['session'], name='student_att_session_9c5889_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['academic_year'], name='student_att_academi_a71093_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendancedata',
            index=models.Index(fields=['attendance', 'student'], name='student_att_attenda_702e0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentattendancedata',
            constraint=models.UniqueConstraint(fields=('student', 'attendance'), name='unique_student_attendance'),
        ),
    ]
