# Generated by Django 5.2.3 on 2025-08-24 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_populate_classes'),
        ('student', '0002_studentattendance_studentattendancedata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.schoolsection'),
        ),
    ]
