# Generated by Django 5.2.3 on 2025-08-14 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('student', '0002_studentattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.schoolacademicyear'),
        ),
    ]
