# Generated by Django 5.2.3 on 2025-08-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('student', '0003_studentattendance_academic_year'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentattendance',
            name='unique_student_date_session',
        ),
        migrations.RenameField(
            model_name='studentattendance',
            old_name='present',
            new_name='is_present',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='taken_by_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(fields=('student', 'date', 'session', 'academic_year'), name='unique_student_date_session_academic_year'),
        ),
    ]
