# Generated by Django 5.2.3 on 2025-09-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentattendance_class_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendancedata',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
