# Generated by Django 5.2.3 on 2025-08-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_studentattendance_unique_student_date_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='updated_by_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
