# Generated by Django 5.2.3 on 2025-09-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentattendancedata_remarks'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='unique_student_id_roll_number',
        ),
    ]
