# Generated by Django 5.2.3 on 2025-08-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_populate_exam_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='max_marks',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='pass_marks',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
