# Generated by Django 5.2.3 on 2025-09-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_exam_max_marks_alter_exam_pass_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
