# Generated by Django 5.2.3 on 2025-07-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_remove_section_school_class_and_more'),
        ('teacher', '0005_alter_subject_name_alter_teacher_teacher_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachersubjectassignment',
            unique_together={('teacher', 'subject', 'school_class')},
        ),
        migrations.RemoveField(
            model_name='teachersubjectassignment',
            name='section',
        ),
    ]
