# Generated by Django 5.2.3 on 2025-09-28 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('classes', '0004_remove_schoolsection_unique_class_instance_section_and_more'),
        ('teacher', '0006_alter_examresult_marks_obtained'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('homework_assigned', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted')], default='pending', max_length=50)),
                ('is_admin_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolacademicyear')),
                ('school_class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.schoolsection')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
            options={
                'db_table': 'teacher_diary',
            },
        ),
    ]
