# Generated by Django 5.2.3 on 2025-07-13 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('classes', '0008_classassignment'),
        ('teacher', '0006_alter_teachersubjectassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachersubjectassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teachersubjectassignment',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
        ),
        migrations.AlterUniqueTogether(
            name='teachersubjectassignment',
            unique_together={('teacher', 'subject', 'school_class', 'academic_year')},
        ),
    ]
