# Generated by Django 5.2.3 on 2025-10-11 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0007_alter_schoollessonplanday_taxonomy_alignment'),
        ('teacher', '0007_teacherdiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus.schoolchapter'),
        ),
        migrations.AddField(
            model_name='exam',
            name='session',
            field=models.CharField(choices=[('m', 'M'), ('a', 'A')], default='m', max_length=1),
        ),
    ]
