# Generated by Django 5.2.3 on 2025-10-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_populate_exam_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
    ]
