# Generated by Django 5.2.3 on 2025-10-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_examresult_is_absent'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
