# Generated by Django 5.2.3 on 2025-08-02 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'school_class_list',
            },
        ),
        migrations.CreateModel(
            name='SchoolSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
                ('board_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'school_section',
            },
        ),
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolacademicyear')),
            ],
            options={
                'db_table': 'class_assignment',
            },
        ),
    ]
