# Generated by Django 5.2.3 on 2025-08-02 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classassignment',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='schoolsection',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.schoolclass'),
        ),
        migrations.AddField(
            model_name='classassignment',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.schoolsection'),
        ),
        migrations.AddConstraint(
            model_name='schoolsection',
            constraint=models.UniqueConstraint(fields=('class_instance', 'section'), name='unique_class_instance_section'),
        ),
        migrations.AlterUniqueTogether(
            name='classassignment',
            unique_together={('class_instance', 'class_teacher', 'academic_year')},
        ),
    ]
