# Generated by Django 5.2.3 on 2025-07-10 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_load_class_section_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='grade',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='school_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='classes.class'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('name', 'grade'), name='unique_name_grade'),
        ),
        migrations.AlterModelTable(
            name='class',
            table='school_class',
        ),
        migrations.AlterModelTable(
            name='section',
            table='class_section',
        ),
    ]
