# Generated by Django 5.2.3 on 2025-09-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_populate_classes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schoolsection',
            name='unique_class_instance_section',
        ),
        migrations.AddConstraint(
            model_name='schoolsection',
            constraint=models.UniqueConstraint(fields=('class_instance', 'section', 'board_id'), name='unique_class_instance_section'),
        ),
    ]
