# Generated by Django 5.2.3 on 2025-07-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_grade_section_school_class_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('name', 'school_class'), name='unique_name_school_class'),
        ),
    ]
