# Generated by Django 5.2.3 on 2025-07-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_section_unique_name_school_class'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='class',
            table='school_class_list',
        ),
        migrations.AlterModelTable(
            name='section',
            table='class_section_list',
        ),
    ]
