# Generated by Django 5.2.3 on 2025-07-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_class_table_alter_section_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='school_class',
        ),
        migrations.RemoveConstraint(
            model_name='class',
            name='unique_name_grade',
        ),
        migrations.RemoveField(
            model_name='class',
            name='grade',
        ),
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('name', 'section'), name='unique_name_section'),
        ),
    ]
