# Generated by Django 5.2.3 on 2025-07-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_remove_section_school_class_and_more'),
        ('teacher', '0006_alter_teachersubjectassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
