# Generated by Django 5.2.3 on 2025-09-01 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_supportticket_ticketresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'available_modules',
            },
        ),
        migrations.CreateModel(
            name='IssueTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'issue_types',
            },
        ),
        migrations.RemoveField(
            model_name='ticketresponse',
            name='is_responder_admin',
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='related_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.availablemodules'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='issue_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.issuetypes'),
        ),
    ]
