# Generated by Django 5.2.3 on 2025-09-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_availablemodules_issuetypes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablemodules',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
