# Generated by Django 5.2.3 on 2025-09-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_populate_modules_and_issuetypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketresponse',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
